package com.github.adamantcheese.chan.features.embedding;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.github.adamantcheese.chan.core.model.PostImage;

import java.util.ArrayList;
import java.util.List;

public class EmbedResult {
    /**
     * The title for this embed result. While this can't be null, also don't make this an empty string either.
     */
    public String title;

    /**
     * An optional duration for this embed. If null and duration parsing is enabled, then another request will be sent to get a duration.
     * If you don't want/have any duration data, set this to an empty string.
     */
    public String duration;

    /**
     * An optional list of post images that is generated by an embedder, if image hotlinking is enabled. Makes some embeds more easily viewable in-app quickly.
     */
    public List<PostImage> extraImages = new ArrayList<>();

    /**
     * An optional target link to use instead of the one in the post if provided.
     */
    public String customLink = null;

    @SuppressWarnings("unused")
    private EmbedResult() {} // for gson, don't use otherwise

    public EmbedResult(
            @NonNull String title, @Nullable String duration, @Nullable PostImage extraImage
    ) {
        this(title, duration, extraImage, null);
    }

    public EmbedResult(
            @NonNull String title, @Nullable String duration, @Nullable PostImage extraImage, @Nullable String customLink
    ) {
        this.title = title;
        this.duration = duration;
        if (extraImage != null) {
            this.extraImages.add(extraImage);
        }
        this.customLink = customLink;
    }

    public EmbedResult(
            @NonNull String title, @Nullable String duration, @Nullable List<PostImage> extraImages
    ) {
        this.title = title;
        this.duration = duration;
        if (extraImages != null) {
            this.extraImages.addAll(extraImages);
        }
    }
}
